# Node.js with Grunt
# Build a Node.js application using the Grunt task runner.
# CodeLaunch YAML help: https://aka.ms/yaml

queue:
  name: 'Hosted VS2017'

#variables:
  # system.debug: 'true'

steps:
- task: Npm@1
  displayName: 'npm install'

- task: Grunt@0
  displayName: 'Run Grunt'
  inputs:
    gruntFile: 'gruntfile.js'
    targets: ''
    publishJUnitResults: 'true'

- task: ArchiveFiles@2
  displayName: 'Create zip file artifact'
  inputs:
    rootFolder: '$(system.defaultWorkingDirectory)'
    includeRootFolder: 'false'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'artifact'
    artifactType: 'container'
